# Generated by Django 4.2.11 on 2026-03-20 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('friends', 'Friends'), ('employers', 'Potential Employers'), ('visitors', 'Regular Visitors')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('date_taken', models.DateField()),
                ('coordinates', models.CharField(blank=True, max_length=255)),
                ('camera_used', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('friends', 'Friends'), ('employers', 'Employers'), ('visitors', 'Visitors')], default='visitors', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.accesspassword')),
            ],
        ),
    ]
