# Generated by Django 4.2.11 on 2026-03-20 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesspassword',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passwordusagelog',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['-date_taken']},
        ),
        migrations.AlterField(
            model_name='passwordusagelog',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='images.accesspassword'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='camera_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='category',
            field=models.CharField(choices=[('friends', 'Friends'), ('employers', 'Potential Employers'), ('visitors', 'Regular Visitors')], default='visitors', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
