# Generated by Django 4.2.11 on 2026-03-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_tag_portfolioimage_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['order', '-date_taken']},
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
