# Generated by Django 4.2.11 on 2026-04-01 12:50

import django.core.validators
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_portfolioimage_options_portfolioimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='is_lossless',
            field=models.BooleanField(default=True, help_text='Image stored in lossless format'),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(upload_to=images.models.portfolio_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'tiff'])]),
        ),
    ]
