# Generated by Django 4.2.11 on 2026-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_portfolioimage_file_size_portfolioimage_is_lossless_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['category'], name='images_port_categor_29d2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioimage',
            index=models.Index(fields=['date_taken'], name='images_port_date_ta_8eed68_idx'),
        ),
    ]
